# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'myfirstacrnetc.azurecr.io/azure-vote-front'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: azure-vote/Dockerfile
  - task: Docker@2
    displayName: Push an image
    inputs:
      repository: $(imageName)
      command: Push
      Dockerfile: azure-vote/Dockerfile
	    containerRegistry : myfirstacrnetc.azurecr.io
