# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'myazureregistry'
  azureVoteImage: 'azure-vote-front'
  azureVoteDockerfile: 'azure-vote/Dockerfile'
  azureVoteImageTag: v2
  redisImage: 'bitnami/redis'
  redisDockerfile: 'redisDockerfile'
  redisImageTag: 6.0.8

steps:
  - task: Docker@2
    displayName: Build and push azure-vote-front image to container registry
    inputs:
      command: buildAndPush
      repository: $(azureVoteImage)
      dockerfile: $(azureVoteDockerfile)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(azureVoteImageTag)
  - task: Docker@2
    displayName: Download and push redis image to container registry
    inputs:
      command: buildAndPush
      repository: $(redisImage)
      dockerfile: $(redisDockerfile)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(redisImageTag)
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'azure-vote'
      publishLocation: 'pipeline'
